#!/usr/bin/env python
from arbiter.Interface.API.System import *
import sys

if sys.argv[1] == 'h' or sys.argv[1] == 'H' or sys.argv[1] == '-h' or sys.argv[1] == '-H':
  print 'usage: MDC-submit-workflow [workflowID]'
  sys.exit(0)

MDC = system()
jobName = str( sys.argv[1] )

MDC.submit(jobName)
